Repository phildini/stayinghomeclub, pull requests merged in 2020-03, with the labels that each got.

#342 Add HASH
  README.md
Labels: awaiting confirmation

#341 Update with FullStory policy
  README.md
Labels: awaiting confirmation

#340 Adding Gem
  README.md
Labels: awaiting confirmation

#325 Add Dstillery
  README.md
Labels: awaiting confirmation

#355 Add Etsy.
  _data/companies.yml
Labels: merge conflict

#338 Added Sulzer US LLC to list
  _data/companies.yml
Labels: awaiting confirmation, merge conflict

#339 add Agoric to README
  _data/companies.yml
  _data/events.yml
Labels: merge conflict

#352 Add Modern Health
  _data/companies.yml
Labels: merge conflict

#364 Adding noble.ai
  _data/companies.yml
Labels: merge conflict

#836 Create edu.bu
  _data/universities/edu.bu.yml
Labels: merge conflict
